// backend/scripts/generateSitemap.js
// Regenerates public/sitemap.xml: the static marketing pages + one <url> per
// college now that /colleges/:id is public (PublicOrDashboardLayout, no login
// wall). Previously the sitemap only listed 5 static pages — zero long-tail
// content for Google to index despite ~8,000+ real college pages existing.
//
// Usage: node scripts/generateSitemap.js
// Requires DATABASE_URL in backend/.env. Safe to re-run (full overwrite).

require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const fs = require('fs');
const path = require('path');
const dbManager = require('../src/config/database');

const DOMAIN = 'https://college-os.vercel.app';
const OUTPUT_PATH = path.join(__dirname, '..', '..', 'public', 'sitemap.xml');

const STATIC_PAGES = [
  { loc: '/', changefreq: 'weekly', priority: '1.0' },
  { loc: '/colleges', changefreq: 'daily', priority: '0.9' },
  { loc: '/terms', changefreq: 'monthly', priority: '0.3' },
  { loc: '/privacy', changefreq: 'monthly', priority: '0.3' },
  { loc: '/ai-disclaimer', changefreq: 'monthly', priority: '0.3' },
  { loc: '/community-guidelines', changefreq: 'monthly', priority: '0.3' },
];

function escapeXml(s) {
  return String(s).replace(/[<>&'"]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' }[c]));
}

async function main() {
  const pool = dbManager.initialize();

  const { rows } = await pool.query(`
    SELECT id, updated_at
    FROM canonical.mv_college_cards
    WHERE canonical_name IS NOT NULL AND LENGTH(TRIM(canonical_name)) > 1
    ORDER BY popularity_score DESC NULLS LAST, global_rank ASC NULLS LAST
  `);

  const urls = [
    ...STATIC_PAGES.map((p) => `  <url>\n    <loc>${DOMAIN}${p.loc}</loc>\n    <changefreq>${p.changefreq}</changefreq>\n    <priority>${p.priority}</priority>\n  </url>`),
    ...rows.map((r) => {
      const lastmod = r.updated_at ? new Date(r.updated_at).toISOString().slice(0, 10) : null;
      return `  <url>\n    <loc>${DOMAIN}/colleges/${escapeXml(r.id)}</loc>${lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : ''}\n    <changefreq>weekly</changefreq>\n    <priority>0.6</priority>\n  </url>`;
    }),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Domain: ${DOMAIN} — generated by backend/scripts/generateSitemap.js, do not hand-edit -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`;

  fs.writeFileSync(OUTPUT_PATH, xml, 'utf8');
  console.log(`Wrote ${urls.length} URLs (${rows.length} colleges + ${STATIC_PAGES.length} static) to ${OUTPUT_PATH}`);
}

main()
  .then(async () => { await dbManager.close(); process.exit(0); })
  .catch(async (err) => {
    console.error('generateSitemap failed:', err);
    try { await dbManager.close(); } catch (_e) { /* noop */ }
    process.exit(1);
  });
