/**
 * Seed scholarships into the scholarships_new table (or scholarships if it exists)
 * Run: node backend/scripts/seedScholarships.js
 */

const dbManager = require('../src/config/database');

const SCHOLARSHIPS = [
  // ── US NATIONAL (Merit-based) ──────────────────────────────────────────────
  {
    name: 'Gates Scholarship',
    provider: 'Bill & Melinda Gates Foundation',
    amount_min: 40000, amount_max: 80000, currency: 'USD',
    scholarship_type: 'need',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior'],
    min_gpa: 3.30,
    deadline_month: 9, deadline_day: 15,
    renewable: true, renewable_years: 4,
    application_url: 'https://www.thegatesscholarship.org',
    description: 'Full scholarship for exceptional, Pell-eligible, minority high school seniors who have demonstrated leadership and academic excellence.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Coca-Cola Scholars Program',
    provider: 'Coca-Cola Scholars Foundation',
    amount_min: 20000, amount_max: 20000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents', 'Temporary Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior'],
    min_gpa: 3.00,
    deadline_month: 10, deadline_day: 31,
    renewable: false,
    application_url: 'https://www.coca-colascholarsfoundation.org',
    description: 'One of the most prestigious college scholarships in the US. 150 scholarships of $20,000 awarded to high school seniors.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Dell Scholars Program',
    provider: 'Michael & Susan Dell Foundation',
    amount_min: 20000, amount_max: 20000, currency: 'USD',
    scholarship_type: 'need',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior'],
    min_gpa: 2.40,
    deadline_month: 12, deadline_day: 1,
    renewable: false,
    application_url: 'https://www.dellscholars.org',
    description: 'Recognizes students who have overcome significant obstacles to pursue higher education. Need-based, first-generation students.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Jack Kent Cooke Foundation Scholarship',
    provider: 'Jack Kent Cooke Foundation',
    amount_min: 40000, amount_max: 55000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior'],
    min_gpa: 3.50,
    deadline_month: 11, deadline_day: 17,
    renewable: true, renewable_years: 4,
    application_url: 'https://www.jkcf.org',
    description: 'Up to $55,000/year for outstanding high school seniors with strong academics who demonstrate significant financial need.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'QuestBridge National College Match',
    provider: 'QuestBridge',
    amount_min: 50000, amount_max: 320000, currency: 'USD',
    scholarship_type: 'need',
    eligible_nationalities: ['All'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior'],
    min_gpa: 3.50,
    deadline_month: 9, deadline_day: 27,
    renewable: true, renewable_years: 4,
    application_url: 'https://www.questbridge.org',
    description: 'Full four-year scholarships to top colleges for low-income students with exceptional academic talent.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'National Merit Scholarship',
    provider: 'National Merit Scholarship Corporation',
    amount_min: 2500, amount_max: 2500, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior'],
    min_gpa: 3.90,
    deadline_month: 10, deadline_day: 15,
    renewable: false,
    application_url: 'https://www.nationalmerit.org',
    description: 'Prestigious merit-based scholarship for students who score in the top percentile on the PSAT/NMSQT.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Buick Achievers Scholarship Program',
    provider: 'General Motors Foundation',
    amount_min: 25000, amount_max: 25000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: ['Engineering', 'Computer Science', 'Business'],
    eligible_years: ['senior', 'freshman', 'sophomore', 'junior'],
    min_gpa: 3.00,
    deadline_month: 2, deadline_day: 1,
    renewable: true, renewable_years: 4,
    application_url: 'https://www.buickachievers.com',
    description: '$25,000/year for STEM students. Special consideration for underrepresented groups in engineering.',
    country: 'USA', is_verified: true,
  },
  // ── DIVERSITY & INCLUSION ─────────────────────────────────────────────────
  {
    name: 'AAUW Selected Professions Fellowship',
    provider: 'American Association of University Women',
    amount_min: 5000, amount_max: 20000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['female', 'non-binary', 'transgender'],
    eligible_majors: ['Engineering', 'Computer Science', 'Mathematics', 'Architecture'],
    eligible_years: ['graduate'],
    min_gpa: 3.00,
    deadline_month: 11, deadline_day: 15,
    renewable: false,
    application_url: 'https://www.aauw.org/resources/programs/fellowships-grants/',
    description: 'For women and nonbinary individuals pursuing graduate degrees in STEM fields where women are underrepresented.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Point Foundation Scholarship',
    provider: 'Point Foundation',
    amount_min: 13500, amount_max: 13500, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'sophomore', 'junior', 'senior', 'graduate'],
    min_gpa: 3.00,
    deadline_month: 1, deadline_day: 18,
    renewable: true, renewable_years: 4,
    application_url: 'https://pointfoundation.org',
    description: 'Scholarship for LGBTQ+ students who have shown leadership and community involvement.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Hispanic Scholarship Fund',
    provider: 'Hispanic Scholarship Fund',
    amount_min: 500, amount_max: 5000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior', 'freshman', 'sophomore', 'junior', 'graduate'],
    min_gpa: 3.00,
    deadline_month: 2, deadline_day: 15,
    renewable: true, renewable_years: 4,
    application_url: 'https://www.hsf.net',
    description: 'The largest Hispanic scholarship fund in the US. Scholarships for students of Hispanic heritage.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'UNCF General Scholarship',
    provider: 'United Negro College Fund',
    amount_min: 500, amount_max: 5000, currency: 'USD',
    scholarship_type: 'need',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior', 'freshman', 'sophomore', 'junior', 'senior'],
    min_gpa: 2.50,
    deadline_month: 3, deadline_day: 31,
    renewable: false,
    application_url: 'https://uncf.org/scholarships',
    description: 'UNCF offers hundreds of scholarships for African American students demonstrating financial need.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Fulbright Scholarship Program',
    provider: 'US State Department / Bureau of Educational and Cultural Affairs',
    amount_min: 15000, amount_max: 50000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['International'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.50,
    deadline_month: 10, deadline_day: 15,
    renewable: false,
    application_url: 'https://foreign.fulbrightonline.org',
    description: 'The US government\'s flagship international educational exchange program. Full funding for graduate study or research in the USA.',
    country: 'USA', is_verified: true,
  },
  // ── INTERNATIONAL / INDIAN STUDENTS ──────────────────────────────────────
  {
    name: 'Inlaks Shivdasani Foundation Scholarship',
    provider: 'Inlaks Shivdasani Foundation',
    amount_min: 30000, amount_max: 100000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.50,
    deadline_month: 4, deadline_day: 1,
    renewable: false,
    application_url: 'https://www.inlaksfoundation.org',
    description: 'For Indian nationals seeking postgraduate degrees at top universities abroad (USA, UK, Europe). Covers tuition, living expenses, travel.',
    country: 'India', is_verified: true,
  },
  {
    name: 'J.N. Tata Endowment Loan Scholarship',
    provider: 'J.N. Tata Endowment',
    amount_min: 500000, amount_max: 1000000, currency: 'INR',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.00,
    deadline_month: 3, deadline_day: 31,
    renewable: false,
    application_url: 'https://www.dorabjitatatrust.org/programmes/jnte/',
    description: 'Loan scholarship for Indian nationals pursuing postgraduate or doctoral studies abroad. Up to ₹10 lakh interest-free.',
    country: 'India', is_verified: true,
  },
  {
    name: 'Aga Khan Foundation International Scholarship',
    provider: 'Aga Khan Foundation',
    amount_min: 10000, amount_max: 50000, currency: 'USD',
    scholarship_type: 'need',
    eligible_nationalities: ['Indian', 'International'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.00,
    deadline_month: 3, deadline_day: 31,
    renewable: false,
    application_url: 'https://www.akdn.org/akf-scholarship',
    description: 'Need-based scholarships for postgraduate students from developing countries (50% grant, 50% loan). Available in select countries.',
    country: 'International', is_verified: true,
  },
  {
    name: 'Commonwealth Scholarship',
    provider: 'UK Commonwealth Scholarship Commission',
    amount_min: 20000, amount_max: 45000, currency: 'GBP',
    scholarship_type: 'merit',
    eligible_nationalities: ['Indian', 'Commonwealth Citizens'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.50,
    deadline_month: 10, deadline_day: 31,
    renewable: false,
    application_url: 'https://cscuk.fcdo.gov.uk/scholarships/',
    description: 'Full scholarships for Commonwealth citizens to study in the UK at master\'s or PhD level. Covers tuition, flight, stipend.',
    country: 'UK', is_verified: true,
  },
  {
    name: 'ICCR Scholarship',
    provider: 'Indian Council for Cultural Relations',
    amount_min: 200000, amount_max: 600000, currency: 'INR',
    scholarship_type: 'grant',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'graduate'],
    min_gpa: null,
    deadline_month: 1, deadline_day: 31,
    renewable: true, renewable_years: 4,
    application_url: 'https://a2ascholarships.iccr.gov.in/',
    description: 'Government of India scholarship for Indian students pursuing higher education abroad. Covers tuition, accommodation, monthly stipend.',
    country: 'India', is_verified: true,
  },
  // ── EDUCATION LOANS FOR INTERNATIONAL STUDENTS ───────────────────────────
  {
    name: 'Prodigy Finance Education Loan',
    provider: 'Prodigy Finance',
    amount_min: 15000, amount_max: 220000, currency: 'USD',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian', 'International'],
    eligible_genders: ['all'],
    eligible_majors: ['Engineering', 'Business', 'Computer Science', 'Law'],
    eligible_years: ['graduate'],
    min_gpa: null,
    deadline_month: null, deadline_day: null,
    renewable: false,
    application_url: 'https://prodigyfinance.com',
    description: 'No cosigner, no collateral education loan for international students at top universities. Based on future earning potential.',
    country: 'International', is_verified: true,
  },
  {
    name: 'MPOWER Financing Loan',
    provider: 'MPOWER Financing',
    amount_min: 2001, amount_max: 100000, currency: 'USD',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian', 'International'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['junior', 'senior', 'graduate'],
    min_gpa: null,
    deadline_month: null, deadline_day: null,
    renewable: false,
    application_url: 'https://www.mpowerfinancing.com',
    description: 'No cosigner, no collateral loans for international and DACA students in the US and Canada. Fixed interest rate.',
    country: 'International', is_verified: true,
  },
  {
    name: 'SBI Global Ed-Vantage Education Loan',
    provider: 'State Bank of India',
    amount_min: 2000000, amount_max: 15000000, currency: 'INR',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'graduate'],
    min_gpa: null,
    deadline_month: null, deadline_day: null,
    renewable: false,
    application_url: 'https://www.sbi.co.in/web/personal-banking/loans/education-loan/global-ed-vantage',
    description: 'SBI\'s education loan for Indian students studying abroad. Up to ₹1.5 crore. No collateral up to ₹40 lakh. Interest subsidy for girl students.',
    country: 'India', is_verified: true,
  },
  {
    name: 'HDFC Credila Education Loan',
    provider: 'HDFC Credila',
    amount_min: 1000000, amount_max: 10000000, currency: 'INR',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'graduate'],
    min_gpa: null,
    deadline_month: null, deadline_day: null,
    renewable: false,
    application_url: 'https://www.hdfccredila.com',
    description: 'Specialized education loan for Indian students studying abroad. Tax benefits available. Competitive interest rates.',
    country: 'India', is_verified: true,
  },
  {
    name: 'Avanse Education Loan',
    provider: 'Avanse Financial Services',
    amount_min: 500000, amount_max: 7500000, currency: 'INR',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'sophomore', 'junior', 'senior', 'graduate'],
    min_gpa: null,
    deadline_month: null, deadline_day: null,
    renewable: false,
    application_url: 'https://www.avanse.com',
    description: 'Education loans for Indian students abroad. Fast processing, up to 100% finance. Both secured and unsecured options.',
    country: 'India', is_verified: true,
  },
  {
    name: 'Axis Bank Education Loan',
    provider: 'Axis Bank',
    amount_min: 500000, amount_max: 7500000, currency: 'INR',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'graduate'],
    min_gpa: null,
    deadline_month: null, deadline_day: null,
    renewable: false,
    application_url: 'https://www.axisbank.com/retail/loans/education-loan',
    description: 'Axis Bank education loan for higher education abroad. Covers tuition, accommodation, books. Tax benefit under 80E.',
    country: 'India', is_verified: true,
  },
  {
    name: 'IDFC FIRST Bank Education Loan',
    provider: 'IDFC FIRST Bank',
    amount_min: 500000, amount_max: 10000000, currency: 'INR',
    scholarship_type: 'loan',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'graduate'],
    min_gpa: null,
    deadline_month: null, deadline_day: null,
    renewable: false,
    application_url: 'https://www.idfcfirstbank.com/personal-banking/loans/education-loan',
    description: 'Education loans up to ₹1 crore for overseas education. Flexible repayment, moratorium during study period.',
    country: 'India', is_verified: true,
  },
  // ── STEM & PROFESSIONAL ────────────────────────────────────────────────────
  {
    name: 'Google Generation Scholarship',
    provider: 'Google',
    amount_min: 10000, amount_max: 10000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents', 'International'],
    eligible_genders: ['female', 'non-binary'],
    eligible_majors: ['Computer Science', 'Engineering', 'Data Science'],
    eligible_years: ['sophomore', 'junior', 'senior', 'graduate'],
    min_gpa: 3.00,
    deadline_month: 12, deadline_day: 1,
    renewable: false,
    application_url: 'https://buildyourfuture.withgoogle.com/scholarships',
    description: 'For women and non-binary students pursuing degrees in computer science or related fields.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Microsoft Research PhD Fellowship',
    provider: 'Microsoft Research',
    amount_min: 42000, amount_max: 42000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents', 'International'],
    eligible_genders: ['all'],
    eligible_majors: ['Computer Science', 'Engineering', 'Mathematics'],
    eligible_years: ['graduate'],
    min_gpa: 3.50,
    deadline_month: 9, deadline_day: 17,
    renewable: true, renewable_years: 3,
    application_url: 'https://www.microsoft.com/en-us/research/academic-program/phd-fellowship/',
    description: 'Full fellowship for PhD students in computing-related fields. Includes stipend, tuition, and conference travel.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'NSF Graduate Research Fellowship',
    provider: 'National Science Foundation',
    amount_min: 34000, amount_max: 34000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'Permanent Residents'],
    eligible_genders: ['all'],
    eligible_majors: ['Engineering', 'Computer Science', 'Biology', 'Chemistry', 'Physics', 'Mathematics'],
    eligible_years: ['senior', 'graduate'],
    min_gpa: 3.50,
    deadline_month: 10, deadline_day: 15,
    renewable: true, renewable_years: 3,
    application_url: 'https://www.nsfgrfp.org',
    description: 'NSF fellowship for graduate students in STEM. $34,000 annual stipend + $12,000 education allowance for 3 years.',
    country: 'USA', is_verified: true,
  },
  // ── CANADIAN SCHOLARSHIPS ─────────────────────────────────────────────────
  {
    name: 'Trudeau Foundation Scholarship',
    provider: 'Pierre Elliott Trudeau Foundation',
    amount_min: 40000, amount_max: 60000, currency: 'CAD',
    scholarship_type: 'merit',
    eligible_nationalities: ['Canadian Citizens', 'International'],
    eligible_genders: ['all'],
    eligible_majors: ['Social Sciences', 'Arts', 'Political Science'],
    eligible_years: ['graduate'],
    min_gpa: 3.80,
    deadline_month: 12, deadline_day: 1,
    renewable: true, renewable_years: 3,
    application_url: 'https://www.trudeaufoundation.ca',
    description: 'Canada\'s most distinguished doctoral scholarship in social sciences and humanities.',
    country: 'Canada', is_verified: true,
  },
  {
    name: 'Vanier Canada Graduate Scholarship',
    provider: 'Government of Canada',
    amount_min: 50000, amount_max: 50000, currency: 'CAD',
    scholarship_type: 'merit',
    eligible_nationalities: ['Canadian Citizens', 'International'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.70,
    deadline_month: 11, deadline_day: 1,
    renewable: true, renewable_years: 3,
    application_url: 'https://vanier.gc.ca',
    description: 'C$50,000/year for 3 years for doctoral students in health, natural sciences, engineering, social sciences, or humanities.',
    country: 'Canada', is_verified: true,
  },
  // ── UK SCHOLARSHIPS ───────────────────────────────────────────────────────
  {
    name: 'Chevening Scholarship',
    provider: 'UK Foreign, Commonwealth & Development Office',
    amount_min: 20000, amount_max: 45000, currency: 'GBP',
    scholarship_type: 'merit',
    eligible_nationalities: ['International', 'Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.00,
    deadline_month: 11, deadline_day: 7,
    renewable: false,
    application_url: 'https://www.chevening.org',
    description: 'UK government\'s flagship scholarship. Fully-funded master\'s degree at any UK university. For future leaders.',
    country: 'UK', is_verified: true,
  },
  {
    name: 'Rhodes Scholarship',
    provider: 'Rhodes Trust',
    amount_min: 35000, amount_max: 50000, currency: 'GBP',
    scholarship_type: 'merit',
    eligible_nationalities: ['US Citizens', 'International'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior', 'graduate'],
    min_gpa: 3.80,
    deadline_month: 10, deadline_day: 1,
    renewable: true, renewable_years: 3,
    application_url: 'https://www.rhodeshouse.ox.ac.uk',
    description: 'Oldest and most prestigious international scholarship. Fully-funded graduate study at Oxford University.',
    country: 'UK', is_verified: true,
  },
  {
    name: 'Gates Cambridge Scholarship',
    provider: 'Bill & Melinda Gates Foundation',
    amount_min: 25000, amount_max: 45000, currency: 'GBP',
    scholarship_type: 'merit',
    eligible_nationalities: ['International', 'US Citizens'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.80,
    deadline_month: 10, deadline_day: 12,
    renewable: true, renewable_years: 4,
    application_url: 'https://www.gatescambridge.org',
    description: 'Fully-funded graduate study at Cambridge University. One of the most prestigious international scholarships.',
    country: 'UK', is_verified: true,
  },
  // ── AUSTRALIA ─────────────────────────────────────────────────────────────
  {
    name: 'Australia Awards Scholarship',
    provider: 'Australian Government',
    amount_min: 40000, amount_max: 80000, currency: 'AUD',
    scholarship_type: 'grant',
    eligible_nationalities: ['International', 'Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.00,
    deadline_month: 4, deadline_day: 30,
    renewable: false,
    application_url: 'https://www.australiaawards.gov.au',
    description: 'Fully-funded scholarships for students from developing countries to study in Australia at postgraduate level.',
    country: 'Australia', is_verified: true,
  },
  // ── FIRST-GEN & COMMUNITY ─────────────────────────────────────────────────
  {
    name: 'Horatio Alger Scholarship',
    provider: 'Horatio Alger Association',
    amount_min: 25000, amount_max: 25000, currency: 'USD',
    scholarship_type: 'need',
    eligible_nationalities: ['US Citizens'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['senior'],
    min_gpa: 2.00,
    deadline_month: 10, deadline_day: 25,
    renewable: false,
    application_url: 'https://scholars.horatioalger.org',
    description: 'For students who have overcome adversity to pursue higher education. $25,000 over 4 years.',
    country: 'USA', is_verified: true,
  },
  {
    name: 'Rotary Foundation Scholarship',
    provider: 'Rotary International',
    amount_min: 15000, amount_max: 30000, currency: 'USD',
    scholarship_type: 'merit',
    eligible_nationalities: ['International', 'All'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['graduate'],
    min_gpa: 3.00,
    deadline_month: 11, deadline_day: 15,
    renewable: false,
    application_url: 'https://www.rotary.org/en/our-programs/scholarships',
    description: 'Scholarships for international graduate students who demonstrate leadership and commitment to community service.',
    country: 'International', is_verified: true,
  },
  {
    name: 'Tata Trust Scholarships',
    provider: 'Tata Trusts',
    amount_min: 100000, amount_max: 3000000, currency: 'INR',
    scholarship_type: 'need',
    eligible_nationalities: ['Indian'],
    eligible_genders: ['all'],
    eligible_majors: [],
    eligible_years: ['freshman', 'graduate'],
    min_gpa: 3.00,
    deadline_month: 3, deadline_day: 31,
    renewable: true, renewable_years: 4,
    application_url: 'https://www.scholarships.tatatrusts.com',
    description: 'Tata Trusts offers a range of scholarships for Indian students pursuing higher education in India and abroad.',
    country: 'India', is_verified: true,
  },
];

async function seedScholarships() {
  let pool;
  try {
    await dbManager.connect();
    pool = dbManager.getDatabase();

    // Determine which table to use
    let tableName = 'scholarships';
    try {
      await pool.query(`SELECT 1 FROM scholarships_new LIMIT 1`);
      tableName = 'scholarships_new';
    } catch {
      try {
        await pool.query(`SELECT 1 FROM scholarships LIMIT 1`);
        tableName = 'scholarships';
      } catch {
        console.error('Neither scholarships nor scholarships_new table exists. Run migration 058 first.');
        process.exit(1);
      }
    }

    console.log(`Seeding ${SCHOLARSHIPS.length} scholarships into ${tableName}...`);
    let inserted = 0, skipped = 0;

    for (const s of SCHOLARSHIPS) {
      try {
        await pool.query(
          `INSERT INTO ${tableName} (
            name, provider, amount_min, amount_max, currency, scholarship_type,
            eligible_nationalities, eligible_genders, eligible_majors, eligible_years,
            min_gpa, deadline_month, deadline_day, renewable, renewable_years,
            application_url, description, country, is_verified
          ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
          ON CONFLICT DO NOTHING`,
          [
            s.name, s.provider, s.amount_min, s.amount_max, s.currency, s.scholarship_type,
            s.eligible_nationalities, s.eligible_genders, s.eligible_majors, s.eligible_years,
            s.min_gpa, s.deadline_month, s.deadline_day, s.renewable, s.renewable_years,
            s.application_url, s.description, s.country, s.is_verified,
          ]
        );
        inserted++;
      } catch (e) {
        // Try without array columns if pg doesn't support them directly
        try {
          await pool.query(
            `INSERT INTO ${tableName} (
              name, provider, amount_min, amount_max, currency, scholarship_type,
              min_gpa, deadline_month, deadline_day, renewable, renewable_years,
              application_url, description, country, is_verified
            ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
            ON CONFLICT DO NOTHING`,
            [
              s.name, s.provider, s.amount_min, s.amount_max, s.currency, s.scholarship_type,
              s.min_gpa, s.deadline_month, s.deadline_day, s.renewable, s.renewable_years,
              s.application_url, s.description, s.country, s.is_verified,
            ]
          );
          inserted++;
        } catch (e2) {
          console.warn(`Skipped "${s.name}": ${e2.message}`);
          skipped++;
        }
      }
    }

    console.log(`Done! Inserted: ${inserted}, Skipped (duplicate/error): ${skipped}`);
  } catch (err) {
    console.error('Fatal error:', err.message);
    process.exit(1);
  } finally {
    process.exit(0);
  }
}

seedScholarships();
