export const CURRICULUM_OPTIONS = [
  'CBSE',
  'ICSE',
  'ISC',
  'State Board',
  'IGCSE',
  'A-Levels',
  'IB DP',
  'IB MYP',
  'AP Curriculum',
  'American High School Diploma',
  'Canadian Curriculum',
  'Australian Curriculum',
  'Cambridge Curriculum',
  'NIOS',
  'Other',
] as const;

export const MAJOR_OPTIONS = [
  'Computer Science',
  'Engineering',
  'Artificial Intelligence',
  'Robotics',
  'Data Science',
  'Cybersecurity',
  'Information Systems',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Biomedical Engineering',
  'Biotechnology',
  'Physics',
  'Mathematics',
  'Statistics',
  'Economics',
  'Finance',
  'Accounting',
  'Business Administration',
  'Entrepreneurship',
  'Marketing',
  'Supply Chain Management',
  'Hospitality Management',
  'Sports Management',
  'Culinary Arts',
  'Psychology',
  'Neuroscience',
  'Sociology',
  'Political Science',
  'Public Policy',
  'International Relations',
  'Legal Studies',
  'Philosophy',
  'Liberal Arts',
  'Environmental Science',
  'Urban Planning',
  'Architecture',
  'Industrial Design',
  'Product Design',
  'Game Design',
  'Human-Computer Interaction',
  'Media Studies',
  'Film',
  'Music Production',
  'Communications',
  'Biology',
  'Chemistry',
  'Undecided',
] as const;

export const SUBJECT_OPTIONS = [
  'Mathematics',
  'Further Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Computer Science',
  'Information Technology',
  'Design Technology',
  'Environmental Science',
  'Environmental Management',
  'Statistics',
  'Data Science',
  'Economics',
  'Business Studies',
  'Accounting',
  'Political Science',
  'Legal Studies',
  'Psychology',
  'Sociology',
  'History',
  'Geography',
  'Philosophy',
  'Global Perspectives',
  'English Language',
  'English Literature',
  'French',
  'Spanish',
  'German',
  'Mandarin Chinese',
  'Hindi',
  'Arabic',
  'Digital Media',
  'Art & Design',
  'Music',
  'Theatre Studies',
  'Film Studies',
  'Physical Education',
  'Health Science',
  'Global Politics',
] as const;

export const TRAIT_OPTIONS = [
  'Creative',
  'Artistic',
  'Experimental',
  'Imaginative',
  'Design-Oriented',
  'Aesthetic Thinker',
  'Visionary',
  'Organizer',
  'Community Builder',
  'Delegator',
  'Strategic Leader',
  'Persuasive',
  'Analytical',
  'Systems Thinker',
  'Problem Solver',
  'Logical',
  'Detail-Oriented',
  'Research-Oriented',
  'Empathetic',
  'Collaborative',
  'Mentor',
  'Communicator',
  'Diplomatic',
  'Listener',
  'Disciplined',
  'Consistent',
  'Competitive',
  'Ambitious',
  'Independent',
  'Self-Starter',
  'Entrepreneurial',
  'Risk-Taker',
  'Builder',
  'Inventor',
  'Product Thinker',
  'Futurist',
  'Humanitarian',
  'Culturally Curious',
  'Ethical Thinker',
  'Sustainability-Oriented',
  'Policy-Oriented',
] as const;

export const SCHOOL_SUGGESTIONS = [
  'Delhi Public School',
  'The British School',
  'American School of Bombay',
  'United World College',
  'Singapore American School',
  'Dulwich College',
  'Canadian International School',
  'GEMS Modern Academy',
  'La Martiniere',
  'St. Xavier\'s School',
  'Kendriya Vidyalaya',
  'National Public School',
];
