-- Data Audit — run in Supabase SQL editor to assess data coverage quality
-- Generated by pre-launch audit. Safe read-only queries.

-- ─────────────────────────────────────────────────────────────────
-- 1. Total college counts by region
-- ─────────────────────────────────────────────────────────────────
SELECT
  country_code,
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE acceptance_rate IS NOT NULL) AS has_acceptance_rate,
  COUNT(*) FILTER (WHERE sat_50 IS NOT NULL OR sat_25 IS NOT NULL) AS has_sat,
  COUNT(*) FILTER (WHERE act_50 IS NOT NULL OR act_25 IS NOT NULL) AS has_act,
  COUNT(*) FILTER (WHERE tuition_international IS NOT NULL) AS has_tuition_intl,
  COUNT(*) FILTER (WHERE cost_of_attendance IS NOT NULL) AS has_coa,
  COUNT(*) FILTER (WHERE graduation_rate_4yr IS NOT NULL) AS has_grad_rate,
  COUNT(*) FILTER (WHERE employment_rate IS NOT NULL) AS has_employment,
  COUNT(*) FILTER (WHERE median_start_salary IS NOT NULL) AS has_salary,
  COUNT(*) FILTER (WHERE global_rank IS NOT NULL) AS has_rank
FROM canonical.mv_college_cards
GROUP BY country_code
ORDER BY total DESC;

-- ─────────────────────────────────────────────────────────────────
-- 2. NULL rate by column (US colleges only)
-- ─────────────────────────────────────────────────────────────────
SELECT
  COUNT(*) AS us_total,
  ROUND(100.0 * COUNT(*) FILTER (WHERE acceptance_rate IS NULL) / COUNT(*), 1) AS pct_missing_acceptance,
  ROUND(100.0 * COUNT(*) FILTER (WHERE sat_50 IS NULL AND sat_25 IS NULL) / COUNT(*), 1) AS pct_missing_sat,
  ROUND(100.0 * COUNT(*) FILTER (WHERE act_50 IS NULL AND act_25 IS NULL) / COUNT(*), 1) AS pct_missing_act,
  ROUND(100.0 * COUNT(*) FILTER (WHERE cost_of_attendance IS NULL) / COUNT(*), 1) AS pct_missing_coa,
  ROUND(100.0 * COUNT(*) FILTER (WHERE graduation_rate_4yr IS NULL) / COUNT(*), 1) AS pct_missing_grad_rate,
  ROUND(100.0 * COUNT(*) FILTER (WHERE employment_rate IS NULL) / COUNT(*), 1) AS pct_missing_employment,
  ROUND(100.0 * COUNT(*) FILTER (WHERE median_start_salary IS NULL) / COUNT(*), 1) AS pct_missing_salary,
  ROUND(100.0 * COUNT(*) FILTER (WHERE global_rank IS NULL) / COUNT(*), 1) AS pct_missing_rank,
  ROUND(100.0 * COUNT(*) FILTER (WHERE avg_financial_aid IS NULL) / COUNT(*), 1) AS pct_missing_aid
FROM canonical.mv_college_cards
WHERE country_code = 'US';

-- ─────────────────────────────────────────────────────────────────
-- 3. Colleges with zero deadline records (application_deadlines)
-- ─────────────────────────────────────────────────────────────────
SELECT
  i.canonical_name,
  i.country_code,
  mv.global_rank
FROM canonical.institutions i
JOIN canonical.mv_college_cards mv ON mv.id = i.id
WHERE NOT EXISTS (
  SELECT 1 FROM public.application_deadlines ad
  JOIN canonical.institution_identity_map m ON m.legacy_id = ad.college_id
  WHERE m.canonical_institution_id = i.id
)
  AND i.country_code = 'US'
  AND mv.global_rank IS NOT NULL
ORDER BY mv.global_rank ASC
LIMIT 50;

-- ─────────────────────────────────────────────────────────────────
-- 4. Colleges in top 200 (US) missing critical data
-- ─────────────────────────────────────────────────────────────────
SELECT
  mv.canonical_name,
  mv.global_rank,
  CASE WHEN mv.acceptance_rate IS NULL THEN 'missing' ELSE 'ok' END AS acceptance_rate,
  CASE WHEN mv.sat_50 IS NULL AND mv.sat_25 IS NULL THEN 'missing' ELSE 'ok' END AS sat,
  CASE WHEN mv.cost_of_attendance IS NULL AND mv.tuition_international IS NULL THEN 'missing' ELSE 'ok' END AS cost,
  CASE WHEN mv.graduation_rate_4yr IS NULL THEN 'missing' ELSE 'ok' END AS grad_rate,
  CASE WHEN mv.median_start_salary IS NULL THEN 'missing' ELSE 'ok' END AS salary
FROM canonical.mv_college_cards mv
WHERE mv.country_code = 'US'
  AND mv.global_rank <= 200
  AND (
    mv.acceptance_rate IS NULL OR
    (mv.sat_50 IS NULL AND mv.sat_25 IS NULL) OR
    mv.graduation_rate_4yr IS NULL
  )
ORDER BY mv.global_rank ASC;

-- ─────────────────────────────────────────────────────────────────
-- 5. Deadline coverage summary
-- ─────────────────────────────────────────────────────────────────
SELECT
  application_year,
  COUNT(DISTINCT college_id) AS colleges_with_deadlines,
  COUNT(*) FILTER (WHERE regular_decision_date IS NOT NULL) AS has_rd,
  COUNT(*) FILTER (WHERE early_action_date IS NOT NULL) AS has_ea,
  COUNT(*) FILTER (WHERE early_decision_1_date IS NOT NULL) AS has_ed1,
  COUNT(*) FILTER (WHERE offers_rolling_admission = TRUE OR offers_rolling_admission = 1) AS has_rolling
FROM public.application_deadlines
GROUP BY application_year
ORDER BY application_year DESC;

-- ─────────────────────────────────────────────────────────────────
-- 6. Identity map coverage (canonical ↔ legacy)
-- ─────────────────────────────────────────────────────────────────
SELECT
  COUNT(*) AS total_canonical_us,
  COUNT(m.legacy_id) AS mapped_to_legacy,
  COUNT(*) - COUNT(m.legacy_id) AS unmapped
FROM canonical.institutions i
LEFT JOIN canonical.institution_identity_map m ON m.canonical_institution_id = i.id
WHERE i.country_code = 'US';
